version: 0.5.{build}

image: Visual Studio 2017

branches:
  only:
  - master
  - develop

configuration:
  - Debug 
  - Release

platform: Any CPU

matrix:
  fast_finish: true

build_script:
  - ps: .\build.ps1 -Script build.cake -Target AppVeyor -Verbosity Diagnostic --settings_skipverification=true

artifacts:
- path: 'artifacts\*.nupkg'
  name: Nuget Packages
- path: 'artifacts\*.md'
  name: Release Notes
- path: 'artifacts\doc'
  name: Api Documentation  

deploy:
- provider: NuGet
  server: https://ci.appveyor.com/nuget/borrillis-tqyvjgcr2l7a
  api_key:
    secure: XNGX8RcDI1BKC2o5VpEzeP9MeOxJr9BBu6JP+kc8veA=
  