# Common configuration for ALL branches
image: Visual Studio 2017

platform: Any CPU

assembly_info:
  patch: false

artifacts:
- path: 'artifacts\*.nupkg'
  name: Nuget Packages
- path: 'artifacts\*.md'
  name: Release Notes
- path: 'artifacts\doc'
  name: Api Documentation  

build_script:
  - ps: .\build.ps1 -Script build.cake -Target AppVeyor -Verbosity Diagnostic --settings_skipverification=true
  
# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# End of Common section
for :

# Overides for `master` branch
-
  branches:
    only:
    - master

  configuration:
    - Release

  matrix:
    fast_finish: true


# Overrides for `merge/*` (PR) branches
-
  branches:
    only:
    - master

  configuration:
    - Debug
    - Release
