name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]  


    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Restore DotNet Tooling
      run: dotnet tool restore
    - name: Initialize build tooling
      run: dotnet cake --bootstrap
    - name: Restore Packages and Dependencies
      run: dotnet restore src/SharpInputSystem.sln
    - name: Build SharpInputSystem
      run: dotnet cake
