name: .NET Core

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Restore dotnet tools
      run: dotnet tool restore
    - name: Initialize build tooling
      run: dotnet cake --bootstrap
    - name: Restore packages and dependencies
      run: dotnet restore src/SharpInputSystem.sln
    - name: Build SharpInputSystem
      run: dotnet cake
